### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by xmha97** [joaomanaia/newquiz#31]
Some contents need an internet connection.

![Screenshot_2023-03-14-02-06-11-659_com.infinitepower.newquiz.jpg](https://user-images.githubusercontent.com/23485114/224848161-d7bfa57a-52d9-4383-848d-4bbb56b163b0.jpg)

I want to use this app offline mode.

**Comment by joaomanaia** [comment]
Hi, some of the game modes of NewQuiz need an internet connection. 

Flag and logo game modes need internet connection because it loads images from web and are not saved on the device. 

Number trivia, multi choice quiz and their categories need internet connection because questions are loaded from an API, for multiple choice quiz you can download questions or save while playing the quiz and then use offline.

I'll still think about saving the flags images so that the flag game mode can be used offline. For now I will update game buttons to show if the game will need internet connection.

**Comment by xmha97** [comment]
Thanks for your reply. 🙏

**Comment by joaomanaia** [comment]
When the game requires internet connection and the user doesn't have internet connection the buttons will be disabled.

**Comment by xmha97** [comment]
It's good, thanks 🙏
